[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x"]
cmds = ["npm install -g pnpm"]

[phases.install]
cmds = [
  "cd ../.. && pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["cd ../.. && pnpm --filter web build"]

[start]
cmd = "pnpm preview"

